cluster:
  mkdir -p logs/{rule}/ &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name={rule}
    --output=logs/{rule}/{jobid}.out
    --error=logs/{rule}/{jobid}.err
    --time={resources.time}
    --parsable
default-resources:
  - mem_mb=3000
  - time=240
  - partition=low2
  - threads=1
jobs: 20
latency-wait: 60
local-cores: 1
restart-times: 1
max-jobs-per-second: 30
max-status-checks-per-second: 20
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
conda-frontend: mamba
cluster-status: ~/.config/snakemake/slurm/slurm-status.py
rerun-triggers:
  - mtime
  - params
  - input
  - software-env
shadow-prefix: /tmp 
cluster-cancel: True
