
basename: 'ms'
output_dir: 'output.ms'

# CSV with at least 3 columns: `name,read1,read2`
samples: 'inputs/ms_samples.csv'

# What samples shall we use for assembly?
# YAML-formatted dictionary of assembly_basename: [samples]
assembly_info: 
  "msC13": 
    - 'msC13app'
    - 'msC13body'
    - 'msC13eye'
  "msA11":
    - 'msA11app'
    - 'msA11body'
    - 'msA11eye'
  "msB20":
    - 'msB20app'
    - 'msB20body'
    - 'msB20eye'

# In addition to the above, should we build an assembly using all samples?
also_assemble_all: False # True


# Maximum memory for Trinity? (integer in mb)

trinity_max_memory: 150000 # 150G
