# non-slurm profile defaults 
restart-times: 3
local-cores: 1
latency-wait: 10
use-conda: True
conda-frontend: mamba
jobs: 1
keep-going: True
rerun-incomplete: True
printshellcmds: True
default-resources:
  - mem_mb=3000
  - time=480
  - partition=med2
  - threads=1
max-jobs-per-second: 1
rerun-triggers:
  - mtime
  - params
  - input
  - software-env
  #- 'code' this is well-intentioned, but keeps resulting in reruns when I change the snakefile in ways unrelated to the rule at hand!!!
